server:
  port: 8003   

spring:
  application:
    name: msa-weather-report-eureka-feign-gateway-hystrix
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  
feign:
  hystrix:
    enabled: true
  client:
    config:
      feign-name:
        connect-timeout: 5000
        read-timeout: 5000
     

  