server:
  port: 8888

spring:
  application:
    name: micro-weather-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sairain/hanxiaojue #github仓库地址
          search-paths:
            - config-repo #仓库下搜索路径
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/   
      