server:
  port: 8008

spring:
  application:
    name: msa-weather-collection-eureka-feign
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/   
      
feign:
  client:
    config:
      feign-name:
        connect-timeout: 5000
        read-timeout: 5000